using Manga.Management.Application.Abstractions;
using Manga.Management.Application.Common;
using Manga.Management.Application.DTOs;
using Manga.Management.Domain.Entities;
using Manga.Management.Domain.Enums;

namespace Manga.Management.Application.Services;

public sealed class ReaderService(IManagementRepository repository, IReaderRepository readerRepository, IManagementUnitOfWork unitOfWork, ICurrentUserService currentUser) : IReaderService
{
    private Guid UserId => currentUser.UserId;
    public async Task<Result<ReaderFavoriteResponse>> AddFavoriteAsync(Guid seriesId, CancellationToken ct = default)
    {
        if (!await IsPublicSeries(seriesId, ct)) return Result<ReaderFavoriteResponse>.Failure("Series is not available for readers.");
        var favorite = await readerRepository.GetFavoriteAsync(UserId, seriesId, ct);
        if (favorite is null) { favorite = new ReaderFavorite { UserId = UserId, SeriesId = seriesId }; await repository.AddAsync(favorite, ct); await unitOfWork.SaveChangesAsync(ct); }
        return Result<ReaderFavoriteResponse>.Success(new ReaderFavoriteResponse { Id = favorite.Id, SeriesId = favorite.SeriesId, CreatedAt = favorite.CreatedAt });
    }
    public async Task<Result<bool>> RemoveFavoriteAsync(Guid seriesId, CancellationToken ct = default) { var item = await readerRepository.GetFavoriteAsync(UserId, seriesId, ct); if (item is not null) { repository.Remove(item); await unitOfWork.SaveChangesAsync(ct); } return Result<bool>.Success(true); }
    public async Task<Result<IReadOnlyList<ReaderFavoriteResponse>>> GetFavoritesAsync(int page, int pageSize, CancellationToken ct = default) => Result<IReadOnlyList<ReaderFavoriteResponse>>.Success(await readerRepository.GetFavoritesAsync(UserId, page, pageSize, ct));
    public async Task<Result<ReaderBookmarkResponse>> AddBookmarkAsync(CreateBookmarkRequest request, CancellationToken ct = default) { if (!await IsPublishedChapter(request.ChapterId, ct)) return Result<ReaderBookmarkResponse>.Failure("Chapter is not available for readers."); var item=await readerRepository.GetBookmarkAsync(UserId, request.ChapterId, request.PageId, ct); if(item is null){item=new ReaderBookmark{UserId=UserId,ChapterId=request.ChapterId,PageId=request.PageId};await repository.AddAsync(item,ct);await unitOfWork.SaveChangesAsync(ct);} return Result<ReaderBookmarkResponse>.Success(new ReaderBookmarkResponse{Id=item.Id,ChapterId=item.ChapterId,PageId=item.PageId,CreatedAt=item.CreatedAt}); }
    public async Task<Result<bool>> RemoveBookmarkAsync(Guid id, CancellationToken ct = default) { var item=await repository.GetByIdAsync<ReaderBookmark>(id,ct); if(item is null||item.UserId!=UserId) return Result<bool>.Failure("Bookmark not found."); repository.Remove(item);await unitOfWork.SaveChangesAsync(ct);return Result<bool>.Success(true); }
    public async Task<Result<IReadOnlyList<ReaderBookmarkResponse>>> GetBookmarksAsync(int page,int pageSize,CancellationToken ct=default)=>Result<IReadOnlyList<ReaderBookmarkResponse>>.Success(await readerRepository.GetBookmarksAsync(UserId,page,pageSize,ct));
    public async Task<Result<ReadingProgressResponse>> SaveProgressAsync(SaveReadingProgressRequest request,CancellationToken ct=default){if(!await IsPublicSeries(request.SeriesId,ct)||!await IsPublishedChapter(request.ChapterId,ct))return Result<ReadingProgressResponse>.Failure("Reading position is not available.");var item=await readerRepository.GetProgressAsync(UserId,request.SeriesId,ct);if(item is null){item=new ReadingProgress{UserId=UserId,SeriesId=request.SeriesId,ChapterId=request.ChapterId,PageId=request.PageId};await repository.AddAsync(item,ct);}else if(request.AllowBackward||await IsLater(request.ChapterId,request.PageId,item.ChapterId,item.PageId,ct)){item.ChapterId=request.ChapterId;item.PageId=request.PageId;item.LastReadAt=DateTime.UtcNow;}await UpsertHistory(item,ct);await unitOfWork.SaveChangesAsync(ct);return Result<ReadingProgressResponse>.Success(ToProgress(item));}
    public async Task<Result<ReadingProgressResponse>> ContinueReadingAsync(CancellationToken ct=default){var item=await readerRepository.GetLatestProgressAsync(UserId,ct);return item is null||!await IsPublishedChapter(item.ChapterId,ct)?Result<ReadingProgressResponse>.Failure("No readable progress found."):Result<ReadingProgressResponse>.Success(ToProgress(item));}
    public async Task<Result<IReadOnlyList<ReadingProgressResponse>>> GetHistoryAsync(int page,int pageSize,CancellationToken ct=default)=>Result<IReadOnlyList<ReadingProgressResponse>>.Success(await readerRepository.GetHistoryAsync(UserId,page,pageSize,ct));
    public async Task<Result<bool>> ClearHistoryAsync(CancellationToken ct=default){foreach(var x in await readerRepository.GetHistoryEntitiesAsync(UserId,ct))repository.Remove(x);await unitOfWork.SaveChangesAsync(ct);return Result<bool>.Success(true);}
    public async Task<Result<RatingSummaryResponse>> RateAsync(Guid seriesId,UpsertRatingRequest request,CancellationToken ct=default){if(request.Value is<1 or>5)return Result<RatingSummaryResponse>.Failure("Rating must be between 1 and 5.");if(!await IsPublicSeries(seriesId,ct))return Result<RatingSummaryResponse>.Failure("Series is not available for readers.");var item=await readerRepository.GetRatingAsync(UserId,seriesId,ct);if(item is null){await repository.AddAsync(new SeriesRating{UserId=UserId,SeriesId=seriesId,Value=request.Value},ct);}else{item.Value=request.Value;item.UpdatedAt=DateTime.UtcNow;}await unitOfWork.SaveChangesAsync(ct);return await GetRatingSummaryAsync(seriesId,ct);}
    public async Task<Result<bool>> RemoveRatingAsync(Guid seriesId,CancellationToken ct=default){var item=await readerRepository.GetRatingAsync(UserId,seriesId,ct);if(item is not null){repository.Remove(item);await unitOfWork.SaveChangesAsync(ct);}return Result<bool>.Success(true);}
    public async Task<Result<RatingSummaryResponse>> GetRatingSummaryAsync(Guid seriesId,CancellationToken ct=default){var ratings=await readerRepository.GetRatingSummaryAsync(seriesId,ct);return Result<RatingSummaryResponse>.Success(new RatingSummaryResponse{SeriesId=seriesId,Count=ratings.Count,Average=ratings.Average});}
    public async Task<Result<ReaderCommentResponse>> AddCommentAsync(Guid? seriesId,Guid? chapterId,CreateCommentRequest request,CancellationToken ct=default){if((seriesId is null)==(chapterId is null)||string.IsNullOrWhiteSpace(request.Content))return Result<ReaderCommentResponse>.Failure("Provide one readable series or chapter and comment content.");if(seriesId.HasValue&&!await IsPublicSeries(seriesId.Value,ct)||chapterId.HasValue&&!await IsPublishedChapter(chapterId.Value,ct))return Result<ReaderCommentResponse>.Failure("Content is not available for readers.");var item=new ReaderComment{UserId=UserId,SeriesId=seriesId,ChapterId=chapterId,Content=request.Content.Trim()};await repository.AddAsync(item,ct);await unitOfWork.SaveChangesAsync(ct);return Result<ReaderCommentResponse>.Success(ToComment(item));}
    public async Task<Result<ReaderCommentResponse>> UpdateCommentAsync(Guid id,UpdateCommentRequest request,CancellationToken ct=default){var item=await repository.GetByIdAsync<ReaderComment>(id,ct);if(item is null||item.UserId!=UserId)return Result<ReaderCommentResponse>.Failure("Comment not found.");if(string.IsNullOrWhiteSpace(request.Content))return Result<ReaderCommentResponse>.Failure("Comment content is required.");item.Content=request.Content.Trim();item.UpdatedAt=DateTime.UtcNow;await unitOfWork.SaveChangesAsync(ct);return Result<ReaderCommentResponse>.Success(ToComment(item));}
    public async Task<Result<bool>> DeleteCommentAsync(Guid id,CancellationToken ct=default){var item=await repository.GetByIdAsync<ReaderComment>(id,ct);if(item is null)return Result<bool>.Failure("Comment not found.");if(item.UserId!=UserId&&!currentUser.IsInRole("Admin"))return Result<bool>.Failure("You do not have permission to delete this comment.");item.DeletedAt=DateTime.UtcNow;item.DeletedByUserId=UserId;await unitOfWork.SaveChangesAsync(ct);return Result<bool>.Success(true);}
    public async Task<Result<IReadOnlyList<ReaderCommentResponse>>> GetCommentsAsync(Guid? seriesId,Guid? chapterId,int page,int pageSize,CancellationToken ct=default)=>Result<IReadOnlyList<ReaderCommentResponse>>.Success(await readerRepository.GetCommentsAsync(seriesId,chapterId,page,pageSize,ct));
    public async Task<Result<ReaderActivitySummaryResponse>> GetActivitySummaryAsync(CancellationToken ct=default)=>Result<ReaderActivitySummaryResponse>.Success(await readerRepository.GetActivitySummaryAsync(UserId,ct));
    private async Task<bool> IsPublicSeries(Guid id,CancellationToken ct){var s=await repository.GetByIdAsync<Series>(id,ct);return s?.Status is SeriesStatus.Ongoing or SeriesStatus.Completed;}
    private async Task<bool> IsPublishedChapter(Guid id,CancellationToken ct){var c=await repository.GetByIdAsync<Chapter>(id,ct);return c?.Status==ChapterStatus.Published&&await IsPublicSeries(c.SeriesId,ct);}
    private async Task<bool> IsLater(Guid chapter,Guid? page,Guid oldChapter,Guid? oldPage,CancellationToken ct){var current=await repository.GetByIdAsync<Chapter>(chapter,ct);var previous=await repository.GetByIdAsync<Chapter>(oldChapter,ct);if(current is null||previous is null)return false;if(current.ChapterNumber!=previous.ChapterNumber)return current.ChapterNumber>previous.ChapterNumber;if(!page.HasValue)return false;var p=await repository.GetByIdAsync<Page>(page.Value,ct);var o=oldPage.HasValue?await repository.GetByIdAsync<Page>(oldPage.Value,ct):null;return p is not null&&(o is null||p.PageNumber>=o.PageNumber);}
    private async Task UpsertHistory(ReadingProgress progress,CancellationToken ct){var item=await readerRepository.GetHistoryAsync(UserId,progress.ChapterId,ct);if(item is null){await repository.AddAsync(new ReadingHistory{UserId=UserId,SeriesId=progress.SeriesId,ChapterId=progress.ChapterId,PageId=progress.PageId,LastReadAt=DateTime.UtcNow},ct);}else{item.PageId=progress.PageId;item.LastReadAt=DateTime.UtcNow;item.VisitCount++;}}
    private static ReadingProgressResponse ToProgress(ReadingProgress x)=>new(){SeriesId=x.SeriesId,ChapterId=x.ChapterId,PageId=x.PageId,LastReadAt=x.LastReadAt};
    private static ReaderCommentResponse ToComment(ReaderComment x)=>new(){Id=x.Id,UserId=x.UserId,SeriesId=x.SeriesId,ChapterId=x.ChapterId,Content=x.Content,CreatedAt=x.CreatedAt,UpdatedAt=x.UpdatedAt};
}
