import React from 'react';
import { RefreshCw, Trophy } from 'lucide-react';
import { IssueResponse, RankingItemResponse } from '@/types/editorial';
import { SeriesResponse } from '@/types/manga';

interface Props { issues: IssueResponse[]; series: SeriesResponse[]; selectedIssueId: string; rankings: RankingItemResponse[]; isLoading: boolean; onIssueChange: (id: string) => void; onReaderVote: (seriesId: string, voteCount: number) => Promise<boolean>; onRecalculate: () => Promise<void>; onRetry: () => Promise<void>; }
export default function RankingTable({ issues, series, selectedIssueId, rankings, isLoading, onIssueChange, onReaderVote, onRecalculate, onRetry }: Props) {
 const [voteSeriesId, setVoteSeriesId] = React.useState(''); const [voteCount, setVoteCount] = React.useState('');
  return <section className="bg-white rounded-2xl border border-slate-100 overflow-hidden">
    <div className="p-5 border-b flex flex-wrap gap-3 items-end justify-between"><div><h2 className="font-bold flex gap-2 items-center"><Trophy size={16}/> Bảng xếp hạng Reader Voting</h2><p className="text-xs text-slate-500">Chọn kỳ phát hành để xem dữ liệu thực.</p></div><div className="flex gap-2"><select aria-label="Publication issue" value={selectedIssueId} onChange={e => onIssueChange(e.target.value)} className="border rounded-lg p-2 text-sm"><option value="">Chọn Issue</option>{issues.map(issue => <option key={issue.id} value={issue.id}>{issue.issueNumber} — {issue.title}</option>)}</select><button onClick={() => void onRecalculate()} disabled={!selectedIssueId || isLoading} className="px-3 py-2 rounded-lg bg-slate-800 text-white text-xs disabled:opacity-50"><RefreshCw size={12} className={isLoading ? 'inline animate-spin mr-1' : 'inline mr-1'}/>Tính BXH</button></div></div>
    {selectedIssueId && <form onSubmit={e => { e.preventDefault(); if (voteSeriesId && voteCount !== '') void onReaderVote(voteSeriesId, Number(voteCount)); }} className="p-4 flex gap-2 border-b"><select aria-label="Reader vote series" value={voteSeriesId} onChange={e => setVoteSeriesId(e.target.value)} required><option value="">Chọn Series</option>{series.map(item => <option value={item.id} key={item.id}>{item.title}</option>)}</select><input aria-label="Reader vote count" type="number" min="0" required value={voteCount} onChange={e => setVoteCount(e.target.value)}/><button disabled={isLoading}>Lưu phiếu</button></form>}{!selectedIssueId ? <p className="p-6 text-sm text-slate-500">Chọn một Issue để tải bảng xếp hạng.</p> : isLoading ? <p className="p-6 text-sm text-slate-500">Đang tải bảng xếp hạng…</p> : rankings.length === 0 ? <div className="p-6 text-sm text-slate-500">Issue này chưa có dữ liệu xếp hạng. <button className="underline" onClick={() => void onRetry()}>Thử lại</button></div> : <table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Hạng</th><th>Series ID</th><th>Phiếu</th><th>Xu hướng</th><th>Rủi ro</th><th>Điểm</th></tr></thead><tbody>{rankings.map(item => <tr key={item.seriesId} className="border-t"><td className="p-3 font-bold">{item.rankPosition}</td><td>{item.seriesId}</td><td>{item.voteCount}</td><td>{item.trend}</td><td>{item.riskLevel}</td><td>{item.score}</td></tr>)}</tbody></table>}
  </section>;
}
