// <auto-generated />
using System;
using Manga.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Manga.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260717055907_AddIdentityAdminClosureHardening")]
    partial class AddIdentityAdminClosureHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Manga.Identity.Domain.Entities.AdminAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("details");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Action", "CreatedAt");

                    b.HasIndex("ActorUserId", "CreatedAt");

                    b.HasIndex("TargetUserId", "CreatedAt");

                    b.ToTable("admin_audit_events", (string)null);
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("group_name");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de301"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View user accounts.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_USER_READ",
                            Name = "Read users"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de302"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Change user status and roles.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_USER_MANAGE",
                            Name = "Manage users"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de321"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create user accounts.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_USER_CREATE",
                            Name = "Create users"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de322"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Update user profiles, status, and roles.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_USER_UPDATE",
                            Name = "Update users"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de323"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft delete user accounts.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_USER_DELETE",
                            Name = "Delete users"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de324"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reset user passwords.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_USER_RESET_PASSWORD",
                            Name = "Reset user passwords"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de325"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Revoke all active refresh tokens.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_USER_SESSION_REVOKE",
                            Name = "Revoke user sessions"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de303"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View configured roles.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_ROLE_READ",
                            Name = "Read roles"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de326"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create, update, and retire custom roles.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_ROLE_MANAGE",
                            Name = "Manage roles"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de327"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Replace permissions assigned to custom roles.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_ROLE_PERMISSION_MANAGE",
                            Name = "Manage role permissions"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de304"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View service health.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_MONITORING_READ",
                            Name = "Read monitoring"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de305"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View outbox messages.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_OUTBOX_READ",
                            Name = "Read outbox"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de306"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Retry failed outbox messages.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_OUTBOX_RETRY",
                            Name = "Retry outbox"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de307"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View audit history.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_AUDIT_READ",
                            Name = "Read audit"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de308"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View system settings.",
                            Group = "Admin",
                            IsSystem = true,
                            Key = "ADMIN_SYSTEM_SETTINGS_READ",
                            Name = "Read system settings"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de309"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "SERIES_CREATE",
                            Name = "Create series"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de310"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "SERIES_MANAGE_OWN",
                            Name = "Manage own series"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de311"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "PAGE_UPLOAD",
                            Name = "Upload page"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de312"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "TASK_READ_ASSIGNED",
                            Name = "Read assigned tasks"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de313"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "TASK_SUBMIT",
                            Name = "Submit task"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de314"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "EDITORIAL_REVIEW_READ",
                            Name = "Read editorial review"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de315"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "EDITORIAL_REVIEW_MANAGE",
                            Name = "Manage editorial review"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de316"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "BOARD_PROPOSAL_READ",
                            Name = "Read board proposals"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de317"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "BOARD_PROPOSAL_VOTE",
                            Name = "Vote board proposals"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de318"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "BOARD_RANKING_READ",
                            Name = "Read rankings"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de319"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "FILE_READ_OWN_OR_ASSIGNED",
                            Name = "Read related files"
                        },
                        new
                        {
                            Id = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de320"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Group = "Business",
                            IsSystem = true,
                            Key = "NOTIFICATION_READ_OWN",
                            Name = "Read own notifications"
                        });
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retired");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator",
                            IsRetired = false,
                            IsSystem = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("1d168ea4-8484-4b3c-8c6a-8cefe7a4f512"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manga creator",
                            IsRetired = false,
                            IsSystem = true,
                            Name = "Mangaka"
                        },
                        new
                        {
                            Id = new Guid("68e9e703-6f32-4b17-9503-6c8d01d56421"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mangaka assistant",
                            IsRetired = false,
                            IsSystem = true,
                            Name = "Assistant"
                        },
                        new
                        {
                            Id = new Guid("91a754e2-2f2d-43c1-825b-c6c861c9f9d2"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assigned editor",
                            IsRetired = false,
                            IsSystem = true,
                            Name = "TantouEditor"
                        },
                        new
                        {
                            Id = new Guid("cf69bb84-449d-40c6-a5a3-31abbb8fe1f0"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Editorial board member",
                            IsRetired = false,
                            IsSystem = true,
                            Name = "EditorialBoard"
                        });
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de301"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de302"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de321"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de322"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de323"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de324"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de325"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de303"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de326"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de327"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de304"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de305"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de306"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de307"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de308"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de309"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de310"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de311"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de312"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de313"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de314"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de315"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de316"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de317"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de318"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de319"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("5c7e1dc3-0271-4b6a-9b4c-0a57f77d8f01"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de320"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("1d168ea4-8484-4b3c-8c6a-8cefe7a4f512"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de309"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("1d168ea4-8484-4b3c-8c6a-8cefe7a4f512"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de310"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("1d168ea4-8484-4b3c-8c6a-8cefe7a4f512"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de311"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("1d168ea4-8484-4b3c-8c6a-8cefe7a4f512"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de319"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("1d168ea4-8484-4b3c-8c6a-8cefe7a4f512"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de320"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("68e9e703-6f32-4b17-9503-6c8d01d56421"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de312"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("68e9e703-6f32-4b17-9503-6c8d01d56421"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de313"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("68e9e703-6f32-4b17-9503-6c8d01d56421"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de319"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("68e9e703-6f32-4b17-9503-6c8d01d56421"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de320"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("91a754e2-2f2d-43c1-825b-c6c861c9f9d2"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de314"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("91a754e2-2f2d-43c1-825b-c6c861c9f9d2"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de315"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("91a754e2-2f2d-43c1-825b-c6c861c9f9d2"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de320"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("cf69bb84-449d-40c6-a5a3-31abbb8fe1f0"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de316"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("cf69bb84-449d-40c6-a5a3-31abbb8fe1f0"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de317"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("cf69bb84-449d-40c6-a5a3-31abbb8fe1f0"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de318"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("cf69bb84-449d-40c6-a5a3-31abbb8fe1f0"),
                            PermissionId = new Guid("b04211be-dc6a-4b5a-a1e7-28308a7de320"),
                            CreatedAt = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("lock_reason");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("locked_by_user_id");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_until");

                    b.Property<string>("NormalizedUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Manga.Identity.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Manga.Identity.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manga.Identity.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Manga.Identity.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manga.Identity.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Manga.Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
